apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft-server
        image: openhack/minecraft-server
        ports:
        - containerPort: 25575
          name: rcon
        - containerPort: 25565
          name: default
        env:
          - name: EULA
            value: "TRUE"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    name: default
  - port: 25575
    name: rcon
  selector:
    app: minecraft-server